### ISSUE TITLE
Merchantconfiguration class path problem

### ISSUE THREAD

**Issue by dickson12** [CyberSource/cybersource-rest-samples-php#8]
Merchantconfiguration class path problem at Resource/ExternalConfiguration.php instead of \CyberSource\Authentication\core\MerchantConfiguration() it should be \CyberSource\Authentication\Core\MerchantConfiguration()

**Comment by ashtru** [comment]
Thank you, @dickson12 
The change is done in https://github.com/CyberSource/cybersource-rest-samples-php/commit/93cc7bddffca66b067ad8ba1015f93f9e1260a49
